version: '3.6'
services:
  server:
    image: name_repo:tag
    build: .
    container_name: name1
  proxy:
    image: nginx
    container_name: name2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080 